var events = require('./binlog_event');
var rowsEvents = require('./rows_event');

var EventCode = {
  UNKNOWN_EVENT: 0x00,
  START_EVENT_V3: 0x01,
  QUERY_EVENT: 0x02,
  STOP_EVENT: 0x03,
  ROTATE_EVENT: 0x04,
  INTVAR_EVENT: 0x05,
  LOAD_EVENT: 0x06,
  SLAVE_EVENT: 0x07,
  CREATE_FILE_EVENT: 0x08,
  APPEND_BLOCK_EVENT: 0x09,
  EXEC_LOAD_EVENT: 0x0a,
  DELETE_FILE_EVENT: 0x0b,
  NEW_LOAD_EVENT: 0x0c,
  RAND_EVENT: 0x0d,
  USER_VAR_EVENT: 0x0e,
  FORMAT_DESCRIPTION_EVENT: 0x0f,
  XID_EVENT: 0x10,
  BEGIN_LOAD_QUERY_EVENT: 0x11,
  EXECUTE_LOAD_QUERY_EVENT: 0x12,
  TABLE_MAP_EVENT: 0x13,
  PRE_GA_DELETE_ROWS_EVENT: 0x14,
  PRE_GA_UPDATE_ROWS_EVENT: 0x15,
  PRE_GA_WRITE_ROWS_EVENT: 0x16,
  DELETE_ROWS_EVENT_V1: 0x19,
  UPDATE_ROWS_EVENT_V1: 0x18,
  WRITE_ROWS_EVENT_V1: 0x17,
  INCIDENT_EVENT: 0x1a,
  HEARTBEAT_LOG_EVENT: 0x1b,
  IGNORABLE_LOG_EVENT: 0x1c,
  ROWS_QUERY_LOG_EVENT: 0x1d,
  WRITE_ROWS_EVENT_V2: 0x1e,
  UPDATE_ROWS_EVENT_V2: 0x1f,
  DELETE_ROWS_EVENT_V2: 0x20,
  GTID_LOG_EVENT: 0x21,
  ANONYMOUS_GTID_LOG_EVENT: 0x22,
  PREVIOUS_GTIDS_LOG_EVENT: 0x23
};

var CodeEvent = [
  'UNKNOWN_EVENT',
  'START_EVENT_V3',
  'QUERY_EVENT',
  'STOP_EVENT',
  'ROTATE_EVENT',
  'INTVAR_EVENT',
  'LOAD_EVENT',
  'SLAVE_EVENT',
  'CREATE_FILE_EVENT',
  'APPEND_BLOCK_EVENT',
  'EXEC_LOAD_EVENT',
  'DELETE_FILE_EVENT',
  'NEW_LOAD_EVENT',
  'RAND_EVENT', 
  'USER_VAR_EVENT',
  'FORMAT_DESCRIPTION_EVENT',
  'XID_EVENT',
  'BEGIN_LOAD_QUERY_EVENT',
  'EXECUTE_LOAD_QUERY_EVENT',
  'TABLE_MAP_EVENT',
  'PRE_GA_DELETE_ROWS_EVENT',
  'PRE_GA_UPDATE_ROWS_EVENT',
  'PRE_GA_WRITE_ROWS_EVENT',
  'WRITE_ROWS_EVENT_V1',
  'UPDATE_ROWS_EVENT_V1',
  'DELETE_ROWS_EVENT_V1',
  'INCIDENT_EVENT',
  'HEARTBEAT_LOG_EVENT',
  'IGNORABLE_LOG_EVENT',
  'ROWS_QUERY_LOG_EVENT',
  'WRITE_ROWS_EVENT_V2',
  'UPDATE_ROWS_EVENT_V2',
  'DELETE_ROWS_EVENT_V2',
  'GTID_LOG_EVENT',
  'ANONYMOUS_GTID_LOG_EVENT',
  'PREVIOUS_GTIDS_LOG_EVENT'
];

var EventClass = {
  UNKNOWN_EVENT: events.Unknown,
  QUERY_EVENT: events.Query,
  ROTATE_EVENT: events.Rotate,
  FORMAT_DESCRIPTION_EVENT: events.Format,
  XID_EVENT: events.Xid,

  TABLE_MAP_EVENT: events.TableMap,
  DELETE_ROWS_EVENT_V1: rowsEvents.DeleteRows,
  UPDATE_ROWS_EVENT_V1: rowsEvents.UpdateRows,
  WRITE_ROWS_EVENT_V1: rowsEvents.WriteRows,
  WRITE_ROWS_EVENT_V2: rowsEvents.WriteRows,
  UPDATE_ROWS_EVENT_V2: rowsEvents.UpdateRows,
  DELETE_ROWS_EVENT_V2: rowsEvents.DeleteRows
};

function getEventName (code) {
  return CodeEvent[code] || 'UNKNOWN_EVENT';
}

function getEventClass (code) {
  return EventClass[getEventName(code)] || events.Unknown;
}

module.exports = {
  getEventName: getEventName,
  getEventClass: getEventClass
};